// import { Inter } from "next/font/google";
'use client';

import { usePathname } from 'next/navigation';
import { AuthProvider } from './AuthContext';

import { Poppins } from 'next/font/google';
import "./globals.css";
import Header from './header/page.js';
import Footer from './footer/page.js'

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['300'],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const noHeaderFooterPaths = ['/adminpanel', '/adminlogin']; 

  const hideHeaderFooter = noHeaderFooterPaths.some((path) => pathname.startsWith(path));

  return (
    <AuthProvider>
    <html lang="en">
      <body className={poppins.className}>
        {hideHeaderFooter ? (
          children
        ) : (
          <>
            <Header />
            {children}
            <Footer />
          </>
        )}
      </body>
    </html>
    </AuthProvider>
  );
}
